# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FirebaseToDo' do

  pod 'React', path: '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'GoogleAppMeasurement', '~> 5.3.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
